version: "3.8"
services:
  db.translate.local:
    container_name: db.translate.local
    image: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - db-backend-volume:/var/lib/postgresql/data
volumes:
  db-backend-volume:
