openapi: 3.0.0
paths:
  /api/v1/health:
    get:
      operationId: HealthController_getHealth
      parameters: []
      responses:
        '200':
          description: Health check
          content:
            application/json:
              schema:
                type: object
                example:
                  status: alive
                properties:
                  status:
                    type: string
                    example: alive
      tags:
        - Health
  /api/v1/translation/find/{uuid}:
    get:
      operationId: TranslationController_findOneByUUID
      parameters:
        - name: uuid
          required: true
          in: path
          description: Dictionary id
          schema:
            type: string
      responses:
        '200':
          description: Returns OK when successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchTranslationResponse'
        '400':
          description: Returns BAD_REQUEST when the payload is invalid or malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Returns NOT_FOUND when no record found with the given uuid
      tags: &ref_0
        - Translation
  /api/v1/translation/create/{uuid}:
    post:
      operationId: TranslationController_create
      parameters:
        - name: uuid
          required: true
          in: path
          example: 12345678-1234-1234-1234-123456789012
          description: UUID of the dictionary
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTranslationRequest'
      responses:
        '201':
          description: Returns CREATED when successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDictionaryResponse'
        '400':
          description: Returns BAD_REQUEST when the payload is invalid or malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Returns UNAUTHORIZED when JWT is not provided, invalid or expired.
          content:
            application/json:
              schema:
                example:
                  statusCode: 401
                  message: Unauthorized
        '403':
          description: Returns FORBIDDEN when JWT is valid but user is not authorized.
          content:
            application/json:
              schema:
                example:
                  statusCode: 403
                  message: Forbidden
        '422':
          description: Returns UNPROCESSABLE_ENTITY when UUID is wrong
      tags: *ref_0
      security:
        - bearer: []
  /api/v1/translation/update/{uuid}:
    patch:
      operationId: TranslationController_update
      parameters:
        - name: uuid
          required: true
          in: path
          description: Dictionary UUID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTranslationRequest'
      responses:
        '204':
          description: Returns NO_CONTENT when successful
        '400':
          description: Returns BAD_REQUEST when the payload is invalid or malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Returns UNAUTHORIZED when JWT is not provided, invalid or expired.
          content:
            application/json:
              schema:
                example:
                  statusCode: 401
                  message: Unauthorized
        '403':
          description: Returns FORBIDDEN when JWT is valid but user is not authorized.
          content:
            application/json:
              schema:
                example:
                  statusCode: 403
                  message: Forbidden
        '422':
          description: Returns UNPROCESSABLE_ENTITY when UUID is wrong
      tags: *ref_0
      security:
        - bearer: []
  /api/v1/translation/delete/{uuid}:
    delete:
      operationId: TranslationController_delete
      parameters:
        - name: uuid
          required: true
          in: path
          description: Dictionary UUID
          schema:
            type: string
      responses:
        '202':
          description: Returns ACCEPTED when successful
        '400':
          description: Returns BAD_REQUEST when the payload is invalid or malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Returns UNAUTHORIZED when JWT is not provided, invalid or expired.
          content:
            application/json:
              schema:
                example:
                  statusCode: 401
                  message: Unauthorized
        '403':
          description: Returns FORBIDDEN when JWT is valid but user is not authorized.
          content:
            application/json:
              schema:
                example:
                  statusCode: 403
                  message: Forbidden
        '422':
          description: Returns UNPROCESSABLE_ENTITY when UUID is wrong
      tags: *ref_0
      security:
        - bearer: []
  /api/v1/dictionary/find/{uuid}:
    get:
      operationId: DictionaryController_findOneByUUID
      parameters:
        - name: uuid
          required: true
          in: path
          description: Dictionary id
          schema:
            type: string
      responses:
        '200':
          description: Returns OK when successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchDictionaryResponse'
        '400':
          description: Returns BAD_REQUEST when the payload is invalid or malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags: &ref_1
        - Dictionary
  /api/v1/dictionary/create:
    post:
      operationId: DictionaryController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDictionaryRequest'
      responses:
        '201':
          description: Returns CREATED when the resource successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDictionaryResponse'
        '400':
          description: Returns BAD_REQUEST when the payload is invalid or malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Returns UNAUTHORIZED when JWT is not provided, invalid or expired.
          content:
            application/json:
              schema:
                example:
                  statusCode: 401
                  message: Unauthorized
        '403':
          description: Returns FORBIDDEN when JWT is valid but user is not authorized.
          content:
            application/json:
              schema:
                example:
                  statusCode: 403
                  message: Forbidden
      tags: *ref_1
      security:
        - bearer: []
  /api/v1/dictionary/update/{uuid}:
    patch:
      operationId: DictionaryController_update
      parameters:
        - name: uuid
          required: true
          in: path
          description: Dictionary UUID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDictionaryRequest'
      responses:
        '204':
          description: Returns NO_CONTENT when successful
        '400':
          description: Returns BAD_REQUEST when the payload is invalid or malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Returns UNAUTHORIZED when JWT is not provided, invalid or expired.
          content:
            application/json:
              schema:
                example:
                  statusCode: 401
                  message: Unauthorized
        '403':
          description: Returns FORBIDDEN when JWT is valid but user is not authorized.
          content:
            application/json:
              schema:
                example:
                  statusCode: 403
                  message: Forbidden
        '422':
          description: Returns UNPROCESSABLE_ENTITY when UUID is wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags: *ref_1
      security:
        - bearer: []
  /api/v1/dictionary/delete/{uuid}:
    delete:
      operationId: DictionaryController_delete
      parameters:
        - name: uuid
          required: true
          in: path
          description: Dictionary UUID
          schema:
            type: string
      responses:
        '202':
          description: Returns ACCEPTED when successful
        '400':
          description: Returns BAD_REQUEST when the payload is invalid or malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Returns UNAUTHORIZED when JWT is not provided, invalid or expired.
          content:
            application/json:
              schema:
                example:
                  statusCode: 401
                  message: Unauthorized
        '403':
          description: Returns FORBIDDEN when JWT is valid but user is not authorized.
          content:
            application/json:
              schema:
                example:
                  statusCode: 403
                  message: Forbidden
        '422':
          description: Returns UNPROCESSABLE_ENTITY when UUID is wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags: *ref_1
      security:
        - bearer: []
  /api/v1/search:
    get:
      operationId: SearchController_searchByKeyword
      parameters:
        - name: keyword
          required: true
          in: query
          description: What keyword to use
          schema:
            type: string
        - name: language
          required: true
          in: query
          description: What language to use
          schema:
            enum:
              - en
              - ru
              - ka
              - me
              - sv
            type: string
        - name: take
          required: false
          in: query
          description: How many MAX records to retrieve
          schema:
            default: 32
            type: number
        - name: skip
          required: false
          in: query
          description: Records to skip
          schema:
            default: 0
            type: number
      responses:
        '200':
          description: Returns OK when successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FetchDictionaryResponse'
        '400':
          description: Returns BAD_REQUEST when the payload is invalid or malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Search
info:
  title: Megrulad.ge Backend Service
  description: Main translation backend service
  version: 0.0.3
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
      name: JWT
      description: Enter JWT auth token
      in: header
  schemas:
    FetchTranslationResponse:
      type: object
      properties:
        uuid:
          type: string
          description: UUID string
          example: 12345678-1234-1234-1234-123456789012
        value:
          type: string
          example: Hello there
          description: Word or sentence
        description:
          type: string
          example: Some explanation
          description: Dictionary word/sentence description, with examples
        language:
          type: string
          example: en
          description: Language code
      required:
        - uuid
        - value
        - description
        - language
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: number
          description: HTTP status code
        message:
          type: string
          description: Error message
        details:
          type: object
          description: Error details
      required:
        - statusCode
        - message
    CreateTranslationRequest:
      type: object
      properties:
        value:
          type: string
          example: Explanation
          description: Word or sentence
        description:
          type: string
          example: Some explanation
          description: Translation word/sentence description, with examples
        language:
          type: string
          example: en
          description: Language code
          enum: &ref_2
            - en
            - ru
            - ka
            - me
            - sv
        source:
          type: string
          description: >-
            Source of the word/sentence, whether it's individually contributed
            by user, or from a dictionary
          default: null
      required:
        - value
        - language
    CreateDictionaryResponse:
      type: object
      properties:
        uuid:
          type: string
          description: UUID string
          example: 12345678-1234-1234-1234-123456789012
        value:
          type: string
          example: Hello there
          description: Word or sentence
        description:
          type: string
          example: Some explanation
          description: Dictionary word/sentence description, with examples
        language:
          type: string
          example: en
          description: Language code
      required:
        - uuid
        - value
        - description
        - language
    UpdateTranslationRequest:
      type: object
      properties:
        value:
          type: string
          example: Explanation
          description: Word or sentence
        description:
          type: string
          example: Some explanation
          description: Translation word/sentence description, with examples
        language:
          type: string
          example: en
          description: Language code
          enum: *ref_2
        source:
          type: string
          description: >-
            Source of the word/sentence, whether it's individually contributed
            by user, or from a dictionary
          default: null
        status:
          type: string
          description: Record status
          enum:
            - ACTIVE
            - INACTIVE
            - DELETED
            - PENDING
            - REJECTED
            - HIDDEN
    TranslationProperty:
      type: object
      properties:
        uuid:
          type: string
          description: UUID string
          example: 12345678-1234-1234-1234-123456789012
        value:
          type: string
          example: Hello there
          description: Word or sentence
        description:
          type: string
          example: Some explanation
          description: Translation word/sentence description, with examples
        language:
          type: string
          example: en
          description: Language code
      required:
        - uuid
        - value
        - description
        - language
    FetchDictionaryResponse:
      type: object
      properties:
        uuid:
          type: string
          description: UUID string
          example: 12345678-1234-1234-1234-123456789012
        value:
          type: string
          example: Hello there
          description: Word or sentence
        description:
          type: string
          example: Some explanation
          description: Dictionary word/sentence description, with examples
        language:
          type: string
          example: en
          description: Language code
        translations:
          type: array
          items:
            $ref: '#/components/schemas/TranslationProperty'
      required:
        - uuid
        - value
        - description
        - language
        - translations
    CreateDictionaryRequest:
      type: object
      properties:
        value:
          type: string
          example: Hello there
          description: Word or sentence
        description:
          type: string
          example: Some explanation
          description: Dictionary word/sentence description, with examples
        language:
          type: string
          example: en
          description: Language code
          enum: &ref_3
            - en
            - ru
            - ka
            - me
            - sv
        source:
          type: string
          description: >-
            Source of the word/sentence, whether it's individually contributed
            by user, or from a dictionary
          default: null
      required:
        - value
        - language
    UpdateDictionaryRequest:
      type: object
      properties:
        value:
          type: string
          example: Hello there
          description: Word or sentence
        description:
          type: string
          example: Some explanation
          description: Dictionary word/sentence description, with examples
        language:
          type: string
          example: en
          description: Language code
          enum: *ref_3
        source:
          type: string
          description: >-
            Source of the word/sentence, whether it's individually contributed
            by user, or from a dictionary
          default: null
        status:
          type: string
          description: Record status
          enum:
            - ACTIVE
            - INACTIVE
            - DELETED
            - PENDING
            - REJECTED
            - HIDDEN
