name: Deploy to GitHub pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.6.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.6.0
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build static documents
        run: npm run gen:docs

      - name: Init new repo in public folder and commit generated files
        run: |
          cd public
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy' --no-verify
      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          force: true
          directory: ./public
