name: Unit/E2E tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  NODE_VERSION: 18.6.0
  REGISTRY_URL: https://npm.pkg.github.com/

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.REGISTRY_URL }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test
